HTML redraw
codex-team/cover-generation pull request #38
Opened 2017-12-07 21:23 UTC by gigafiga21

#### Reason:
SVG was not the best way to work with. Changed canvas type to HTML, added redrawing class which converts HTML to HTMLCanvas.

#### Works:
- text editing and adding
- adding and editing images
- saving to png (only text)

#### In next request:
- add ability to use multistring text
- add another CSS class especially for working with images
- fix problem with converting HTML containing image to the HTMLCanvas

2017-12-07 22:14 UTC, neSpecc requested changes

2017-12-07 22:14 UTC, neSpecc commented on src/canvas.js
> +        this.tree.svg.classList.add(this.CSS.canvas);
класс можно в make передать

2017-12-07 22:14 UTC, neSpecc commented on src/redrawer.js
> +export default class Redrawer {
класс нужно задокументировать примерно так

![image](https://user-images.githubusercontent.com/3684889/33741294-ceef7c28-dbb4-11e7-9693-2e5008a2d8a6.png)

2017-12-07 22:14 UTC, neSpecc commented on src/redrawer.js
> +        regexp = /^\s/g;
эти два можно заменить на .trim()

2017-12-07 22:14 UTC, neSpecc commented on src/redrawer.js
> +        image.src = element.getAttribute('SRC');
src

2017-12-08 08:59 UTC, gigafiga21 commented on src/redrawer.js
> +        regexp = /^\s/g;
Trim не удаляет переносы строк и символы табуляции(

2017-12-08 12:58 UTC, neSpecc requested changes

2017-12-08 12:58 UTC, neSpecc commented on src/redrawer.js
> +        regexp = /^\s/g;
удаляет. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim

2017-12-08 12:58 UTC, neSpecc commented on src/toolbar.js
> +        while (element && element.offsetTop !== undefined && element.offsetLeft !== undefined) {
я это уже где-то видел. Можно вынести метод в dom. а еще погугли `getBoundingClientRect`

2017-12-08 14:45 UTC, gigafiga21 commented on src/toolbar.js
> +        while (element && element.offsetTop !== undefined && element.offsetLeft !== undefined) {
Я знаю что это. Помню, меня попросили это не юзать.

2017-12-14 17:12 UTC, neSpecc approved these changes

2017-12-14 17:17 UTC, merged